global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ribeirazul-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Application metrics
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8081']
        labels:
          service: 'api-gateway'

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth:8084']
        labels:
          service: 'auth'

  - job_name: 'properties-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['properties:8082']
        labels:
          service: 'properties'

  - job_name: 'media-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['media:8083']
        labels:
          service: 'media'

  - job_name: 'settings-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['settings:8085']
        labels:
          service: 'settings'

  - job_name: 'users-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['users:8086']
        labels:
          service: 'users'
