# Configuração Manual Traefik - Ribeira Azul
# Domínio: neodras.com
# Gerado automaticamente pelo SuperHomem da Arquitetura 🚀

http:
  # ====================================
  # ROUTERS - Definição de rotas
  # ====================================
  routers:
    # Router principal para o frontend
    neodras-web:
      rule: "Host(`neodras.com`) || Host(`www.neodras.com`)"
      service: neodras-web-service
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-https
        - security-headers

    # Router para API Gateway
    neodras-api:
      rule: "Host(`neodras.com`) && PathPrefix(`/api`)"
      service: neodras-api-service
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - redirect-to-https
        - security-headers
        - api-cors

    # Router para health checks
    neodras-health:
      rule: "Host(`neodras.com`) && PathPrefix(`/health`)"
      service: neodras-web-service
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt

  # ====================================
  # SERVICES - Definição de serviços
  # ====================================
  services:
    # Serviço do Frontend (Nginx)
    neodras-web-service:
      loadBalancer:
        servers:
          - url: "http://web:80"
        healthCheck:
          path: "/health"
          interval: "30s"
          timeout: "10s"

    # Serviço do API Gateway
    neodras-api-service:
      loadBalancer:
        servers:
          - url: "http://api-gateway:8081"
        healthCheck:
          path: "/health"
          interval: "30s"
          timeout: "10s"

  # ====================================
  # MIDDLEWARES - Configurações extras
  # ====================================
  middlewares:
    # Redirect HTTP para HTTPS
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    # Headers de segurança
    security-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "https://neodras.com"
          - "https://www.neodras.com"
        accessControlMaxAge: 100
        addVaryHeader: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"

    # CORS específico para API
    api-cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
          - "X-Requested-With"
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "https://neodras.com"
          - "https://www.neodras.com"

# ====================================
# TCP/UDP Configuration (se necessário)
# ====================================
tcp:
  routers: {}
  services: {}

udp:
  routers: {}
  services: {}
